spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/automobile?createDatabaseIfNotExist=true

pumba:
  path:
    image:
      cooperating-organization: E:\pumba
      car: /var/images/car
  baseUrl: http://3.75.198.120:8080/api
