spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/automobile
    username: root
    password: root

pumba:
  path:
    image:
      cooperating-organization: /var/pumba
      car: /var/images/car/
  baseUrl: http://localhost:8080/api
