spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/automobile?createDatabaseIfNotExist=true
    username: root

pumba:
  path:
    image:
      cooperating-organization: /var/pumba
      car: /var/images/car
  baseUrl: http://3.75.198.120:8080/api
